
POST http://localhost:3000/task
content-type: application/json

{
    "type": "REQUEST",
    "execute_at": "2025-03-14T12:00:00.000Z",
    "payload": {
        "url": "123",
        "payload": "456",
        "token": "789"
    }
}

###


GET http://localhost:3000/task

###